### ISSUE TITLE
Docker upgrades

### ISSUE THREAD

**Issue by vitobotta** [simonfrey/matomo_circumvent_adblock#4]
Hi! What are we supposed to do when we upgrade the Matomo Docker image? I had forgotten about the changes I made with this script and just updated Matomo (both image and from the web interface). Tracking still seems to work, I think. Am I supposed to re-run the script or do something when upgrading Matomo? Thanks!

**Comment by simonfrey** [comment]
Yes, you need to rerun the script as the old config file would be deleted.
