### ISSUE TITLE
No longer functions

### ISSUE THREAD

**Issue by BlueHairMinerBoy** [simonfrey/matomo_circumvent_adblock#5]
This no longer works, uBlock is blocking the PHP script under the following rule: "*$ping,3p"

**Comment by jsvtrlvrslv** [comment]
Let's wait for Simon... :(

**Comment by simonfrey** [comment]
Any ideas how we could update the script to cirumvent that rule?

**Comment by simonfrey** [comment]
I assume we would need to entire rewrite the matomo local javascript, to not use "ping" requests anymore.

**Comment by simonfrey** [comment]
Okay I found a fix :D When you add ` _paq.push(['disableAlwaysUseSendBeacon', 'true']);` to the tracking script, it does not use the beacon approach and is cleard by ublcok
